[project]
name = "my-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DamPhuQuy", email = "phuquydam06@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "librosa>=1.0.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pywavelets>=1.10.0",
    "scipy>=1.18.1",
    "sounddevice>=0.5.6",
    "soundfile>=0.14.0",
]

[project.scripts]
my-setup = "my_setup:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
